version: '3.5'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - ./app.env
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file:
      - ./db.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
